---
title: "hw5"
author: "박지은"
date: '2019 9 16 '
output: html_document
---
## 1번 
```{r}
library(datasets)
head(Orange,10)
boxplot(circumference~Tree,data = Orange)$stat
```

## 2번
```{r}
boxplot(x=Orange$age,range=1.2,xlab='age')
points(mean(Orange$age),col='red',cex=2)
points(sd(Orange$age),col='blue',cex=2)
hist(Orange$circumference,xlab='circumference',5,col=c('red','orange','yellow','green','blue'))
```

## 3번
```{r}
complaint = c( "o" ,"o", "n", "j", "c", "f","b" ,"b","f" ,"o" ,"j" ,"o" ,"o", "m", "o", "f", "f", "o", "o", "n", "o", "n" ,"j", "f", "j", "b", "o", "c", "j", "o", "j", "j", "f", "n","o", "b", "m", "o", "j" ,"m", "o" ,"b", "o", "f", "j", "o", "o", "b", "n", "c", "o", "o", "o", "m", "b", "f" ,"j", "o", "f", "n")
complaint = toupper(complaint)
complaint[complaint=="N"]="C"
complaint_table = addmargins(table(complaint))
complaint_table

```

## 4번
```{r}
pie(x=table(complaint),labels =
      c("B","C","F","J","M","O"),lty=1,main="건강에 대한 불편함의 형태")

```

## 5번
```{r}
i=1
x=rep(0,10)

while (i <= 10) {
  x[i]=2^i
  i = i+1
}
mean(x)
sd(x)
```

## 6번
```{r}
library(dplyr)
x = data.frame(x)
xx = x %>%  filter(x<500)
mean(xx$x)
sd(xx$x)
```

## 7번
```{r}
addmargins(table(airquality[,c(5,4)]))
str(airquality)
y = airquality %>% 
    select(Temp,Month) %>% 
    filter(Month>=6 & Month<=8) %>% 
    filter(Temp >= 90)
y = data.frame(y)
yy=table(y$Month)
barplot(yy,main='월별 고온 횟수',xlab='월',ylab='횟수',col='lightpink')
```

