---
title: "hw_12"
author: "박지은"
date: '2019 11 22 '
output: html_document
---
# 1번
```{r}

# 1-1
str(iris)
iris_n = iris[c(1,2,3,4)]
fit1 = lm(Sepal.Length~., iris_n)
fit1

# 1-2
summary(fit1)
# 각 변수들은 p-value가 0.05보다 작으므로 유의하다. 그리고 모형은 F-통계량의 p-value가 0.05보다 작으므로 유의하다. 결정계수는 0.8586으로 회귀식을 통해 85.86% 설명을 할 수 있음을 알 수 있다.

# 1-3
library(car)
vif(fit1)

# 1-4
fit2 = lm(Sepal.Length~., -Petal.Length, data=iris_n)
fit2
vif(fit2)

# 1-5
summary(fit1)
summary(fit2)
plot(iris_n)
# fit1에서 Petal.Width의 회귀계수는  -0.55648로 음의 상관관계를 갖고 fit2에서 Petal.Width의 회귀계수는 0.97213로 양의 상관곤계를 갖는다.
# Petal.Length와 Sepal.Length는 양의 상관관계이기는 하나 그룹을 지어 나누는 것이 더 의미 있어 보인다.

# 1-6
# fit1에서는 Petal.Width의 회귀계수가 음의 상관관계를 갖는다는 수치를 보여주었으나, 산점도를 보면 약한 양의 상관관계를 갖음을 볼 수 있다. 이는 독립성이 위배되는 회귀모델은 각 변수가 반응변수에 주는 영향을 왜곡해서 보여줄 수 있음을 보여준다.  따라서 다중공선성을 띄는 변수는 제거가 필요하다.
```

# 2번
```{r}
# 2-1
HR = read.csv("C:/Users/danan/Desktop/비타민/정규수업_R/12주차/HR.csv",
                           header = TRUE,sep=',',
                           stringsAsFactors = FALSE)
colSums(is.na(HR))
HR_n = na.omit(HR)
colSums(is.na(HR_n))
HR_n = HR_n[-7]
str(HR_n)

# 2-2
HRfit = lm(left~., data=HR_n)
HRfit

# 2-3
vif(HRfit)

# 2-4
summary(HRfit)

#2-5 
#퇴사를 가장 높이는 요인은 last_evaluation이다. 그리고 가장 낮추는 요인은 satisfaction_level이다. 

# 2-6
last_evaluation = 0.8
number_project = 5
average_montly_hours = 240
time_spend_company = 4
Work_accident = 0
promotion_last_5years = 0
satisfaction_level = 0.5
re.equ = 0.4810487+0.0998774*last_evaluation-0.0345928*number_project+0.0006472*average_montly_hours+0.0334441*time_spend_company-0.1567398*Work_accident-0.1611349*promotion_last_5years-0.6591152*satisfaction_level
re.equ
```

