---
title: "Untitled"
author: "이정민"
date: '2019 11 24 '
output: html_document
---
#1번
```{r}
attach(iris)
iris_n<-iris[,-5]
fit1<-lm(Sepal.Length~Sepal.Width+Petal.Length+Petal.Width,data=iris_n)
fit1
summary(fit1)
library(car)
vif(fit1)
iris_1<-iris_n[,-3]
fit2<-lm(Sepal.Length~Sepal.Width+Petal.Width,data=iris_1)
fit2
vif(fit2)
plot(iris_n)
```
#1-2에서 분포의 피밸류가 유의수준보다 크므로 회귀분석이 타당하다고 볼 수 있고 변수별 피밸류도 다 유의수준보다 작아서 다 유의미하다고 볼 수 있다. 1-5에서 Petal.Width의 추정값이 다 양수이므로 양의 상관관계를 가진다고 할 수 있다.

#2번
```{r}
setwd("C:/Users/danan/Desktop/비타민/정규수업_R/12주차")
hr<-read.csv("HR.csv",header = TRUE,sep=',',stringsAsFactors = FALSE)
hr1<-hr[,-7]
library(dplyr)
HR_n<-hr1 %>% filter(!is.na(last_evaluation)) %>% 
  filter(!is.na(number_project)) %>% 
  filter(!is.na(average_montly_hours)) %>% 
  filter(!is.na(time_spend_company)) %>% 
  filter(!is.na(Work_accident)) %>% 
  filter(!is.na(promotion_last_5years)) %>% 
  filter(!is.na(satisfaction_level)) %>% 
  filter(!is.na(left))
attach(HR_n)
HRfit<-lm(left~last_evaluation+number_project+average_montly_hours+time_spend_company+Work_accident+promotion_last_5years+satisfaction_level,data=HR_n)
HRfit
vif(HRfit)
summary(HRfit)
last_evaluation1<-0.8
number_project1<-5
average_montly_hours1<-240
time_spend_company1<-4
Work_accident1<-0
promotion_last_5years1<-0
satisfaction_level1<-0.5
re.equ<-0.4810487+0.0998774*last_evaluation1-0.0345928*number_project1+0.0006472*average_montly_hours1+0.0334441*time_spend_company1-0.1567398*Work_accident1-0.1611349*promotion_last_5years1-0.6591152*satisfaction_level1
re.equ
```
#2-4에서 변수,모형 모두 유의미하다. 퇴사를 가장 높이는 요인:last_evaluation, 가장 낮추는 요인:satisfaction_level