---
title: "test"
author: "박지은"
date: '2019 10 2 '
output: html_document
---
## 1번
```{r}
stairs = data.frame(x = matrix(rep(NA,45),nrow=9))

for(i in 1:9){
  if(i<=5){
    stairs[i,]=c(1:i,rep(NA,5-i)) } else {
      stairs[i,] = c(1:(10-i),rep(NA,i-5))
    }
  }

print(stairs)
```

## 2번(1)
```{r}
data = read.table(file='C:/Users/danan/Desktop/비타민/정규수업_R/시험/비타민_중간고사/middle_data.txt',sep=",",header=TRUE)
head(data[,48:50])
data = replace(data,data=="?",NA)
head(data[,48:50])

```

## 2번(2)
```{r}
pMiss = function(x){
  perc = rep(0,length(ncol(x)))
  for (i in 1:ncol(x)){
   perc[i] =(sum(is.na(x[,i]))/nrow(x)) * 100
  }
  return (perc)}
pMiss(data)

data2 = data[,pMiss(data)<5]
ncol(data2)
```

## 2번(3)
```{r}
a = as.numeric(data2$Albumin)
b = mean(a,na.rm=T)
b
data2$Albumin = ifelse(is.na(a),b,a)
sum(is.na(data2$Albumin))
```

## 2번(4)
```{r,error=T}
attach(data2)
Albumin.cat = ifelse(Albumin >= 1.5 & Albumin<2.5,0,
                     ifelse(Albumin>=2.5 & Albumin <3.5,1,
                            ifelse(Albumin>=3.5 & Albumin<4.5,2,
                                   ifelse(Albumin >4.5,3,NA)))
detach(data2)
data2 = cbind(data2,Albumin.cat)
table(data2$Albumin.cat)


```

## 2번(5)
>> 장점은 보기 편하고 단점은 자세히 알 수 없다 