---
title: "hw4"
author: "박지은"
date: "2019년 9월 4일"
output: html_document
---
## 1번
```{r}
library(dplyr)
library(ggplot2)
diamonds = as.data.frame(ggplot2 :: diamonds)
diamonds %>% 
  filter( clarity == "SI2") %>% 
  filter( price <= 400) 
```

## 2번
```{r}
diamonds %>% 
  select(contains("a"))
```

## 3번 
```{r}
diamonds %>% 
  group_by(cut) %>% 
  summarise(mean_price = mean(price)) %>% 
  arrange(desc(mean_price)) %>% 
  head(3)
```

## 4번 
```{r}
bitamin = data.frame(sex = c("F","F","M","F","M","M","F","F","M","M"), 
                     test= c(65, 70,77,82,97,86,55,99,67,85))
bitamin
```

## 5번
```{r}
bitamin_a = cbind(bitamin, grade = ifelse(bitamin$test < 65,'F',ifelse(bitamin$test >= 65 & bitamin$test <75, 'C', ifelse(75<=bitamin$test & bitamin$test < 85, 'B', ifelse(85<= bitamin$test,'A','other')))))
bitamin_a
```

## 6번
```{r}
bitamin_a %>% 
  group_by(sex) %>% 
  summarise(mean(test),sd(test),n())
```

## 7번
```{r}
bitamin_b = data.frame(sex=c('F','M'),
                       code = c(1,2))
left_join(bitamin,bitamin_b,by = "sex") %>% 
  arrange(code,desc(test))
```