---
title: "hw6"
author: "박지은"
date: '2019 9 20 '
output: html_document
---
## 1번
```{r}
library(ggplot2)
d = as.data.frame(diamonds)
ggplot(d,aes(x=clarity, fill=cut))+ 
  geom_bar(position = 'dodge') +
  theme_dark() +
  ggtitle('Diamonds') + 
  theme(plot.title = element_text(face='bold.italic',
                                  size = 30,
                                  hjust=0.5))
```

## 2번
```{r}
ggplot(data=mpg,
       aes(x=class,y=cty))+
  geom_boxplot(fill='skyblue',outlier.color='red',outlier.shape=4,width=0.3)+
  theme_minimal()+
  theme(axis.text.x =element_text(size=12,face='bold.italic'),
        axis.text.y =element_text(size=12,face='bold.italic'),
        axis.title=element_text(size=15,face='bold.italic'))
```

## 3번
```{r}
data_temp=data.frame(month = c(1:12),
                     temp = c(1,4,11,18,23,26,28,29,35,18,11,4))
data_temp
ggplot(data_temp,aes(x=month,y=temp))+
  geom_line(size=2,color='lightskyblue')+
  ggtitle('월 최고 기온')+
  labs(x='월',y='기온')+
  scale_x_continuous(breaks=c(1:12))+
  scale_y_continuous(breaks=c(seq(0,35,5)))
```

## 4번
```{r}
library(dplyr)
new_air = airquality %>%
  select(-Month, -Day) %>% 
  na.omit
head(new_air)  
cor(new_air)

library(corrplot)
cor_air = cor(new_air)
corrplot(cor_air,method=c("ellipse"))

```

## 5번
```{r}
library(treemap)
dia = data.frame(diamonds)
dia = diamonds %>% select(cut,clarity,price)
sum_of_price=aggregate(price~.,data=dia,sum)
treemap(sum_of_price,vSize='price',index=c("cut",'clarity'),title='sum_of_price')

```