---
title: "hw11"
author: "박지은"
date: '2019 11 15'
output: html_document
---
## 1번
```{r}
method_A = c(6, 7, 3, 8, 4, 4, 7, 4, 2, 5, 4, 3, 5, 2, 6, 5, 2, 3, 5, 6, 3, 4)
method_B = c(7, 6, 5, 8, 6, 4, 9, 4, 5, 6, 4, 5, 3, 2, 3, 4, 3, 4, 5, 3, 5, 5)

# 1-1
#H0 : A의 암기력 = B의 암기력   
#H1 : A의 암기력 != B의 암기력 

# 1-2
#H0 : 두 모집단이 정규분포를 따른다
#H1 : 두 모집단이 정규분포를 따르지 않는다.
shapiro.test(method_A)
# p-value가 0.05보다 크므로 귀무가설을 기각할 수 없다. 유의수준 5% 하에서 따라서 정규분포를 따른다고 할 수 있다.
shapiro.test(method_B)
# p-value가 0.05보다 크므로 유의수준 5% 하에서 귀무가설을 기각할 수 없다. 따라서 정규분포를 따른다고 할 수 있다. 

# 1-3
#H0 : v1 = v2
#H1 : v1 != v2
var.test(method_A, method_B)
# p-value가 0.05보다 크므로 유의수준 5% 하에서 귀무가설을 기각할 수 없다. 따라서 두 집단의 분산은 같다고 할 수 있다.

# 1-4
# H0 : m1 = m2
# H1 : m1 != m2
t.test(method_A, method_B, paired = T)
# p-value가 0.05보다 크므로 유의수준 5% 하에서 귀무가설을 기각할 수 없다. 따라서 두 방법 간의 차이가 있다고 할 수 없다.
#즉, 1-1에서 세웠던 가설을 보면 방법 A와 방법 B의 암기력에 차이가 있다고 볼 수 없다.
```

## 2번
```{r}
n1 = 40
n2 = 50
x1 = 70
s1 = 10
x2 = 83
s2 = 12

# 2-1
# H0 : mu2-mu1 = 10
# H1 : not H0

# 2-2
sp2 = ((n1-1)*s1^2 + (n2-1)*s2^2)/(n1+n2-2)
t1 = (x2 - x1)/(sp2*sqrt(1/n1+1/n2))
t1

# 2-3
t2 = (x2-x1)/sqrt(s1^2/n1 + s2^2/n2)
t2

# 2-4
z = (x2-x1)/sqrt(s1^2/n1 + s2^2/n2)
z
p_value = 2*pnorm(-abs(z))
p_value
p_value < 0.1
# p-value 값이 0.1 보다 작으므로 유의수준 10%하에서 귀무가설을 기각할 수 있다. 즉 두 집단의 성적 차이가 10점이라고 할 수 없다.
```

## 3번
> 1, 2, 3
